<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'create.membership',
            'show.membership',
            'edit.membership',
            'delete.membership',
            'view.reports',
            'export.reports',
            'manage.users',
            'assign.roles',
            'revoke.roles',
            'create.posts',
            'edit.posts',
            'delete.posts',
            'publish.posts',
            'unpublish.posts',
            'approve.comments',
            'delete.comments',
            'view.analytics',
            'manage.settings',
            'backup.database',
            'restore.database',
            'schedule.tasks',
            'cancel.tasks',
            'view.logs',
            'clear.logs',
            'manage.notifications',
            'send.notifications',
            'view.invoices',
            'generate.invoices',
            'pay.invoices',
            'refund.invoices',
            'manage.subscriptions',
            'cancel.subscriptions',
            'renew.subscriptions',
            'view.users',
            'block.users',
            'unblock.users',
            'reset.passwords',
            'view.roles',
            'create.roles',
            'edit.roles',
            'delete.roles',
            'view.permissions',
            'create.permissions',
            'edit.permissions',
            'delete.permissions',
            'assign.permissions',
            'revoke.permissions',
            'view.categories',
            'create.categories',
            'edit.categories',
            'delete.categories',
            'view.tags',
            'create.tags',
            'edit.tags',
            'delete.tags',
            'view.products',
            'create.products',
            'edit.products',
            'delete.products',
            'view.orders',
            'create.orders',
            'edit.orders',
            'delete.orders',
            'process.orders',
            'ship.orders',
            'track.orders',
            'cancel.orders',
            'view.customers',
            'create.customers',
            'edit.customers',
            'delete.customers',
            'view.reviews',
            'approve.reviews',
            'reject.reviews',
            'delete.reviews',
            'view.discounts',
            'create.discounts',
            'edit.discounts',
            'delete.discounts',
            'apply.discounts',
            'view.coupons',
            'create.coupons',
            'edit.coupons',
            'delete.coupons',
            'redeem.coupons',
            'view.transactions',
            'create.transactions',
            'edit.transactions',
            'delete.transactions',
            'view.shipments',
            'create.shipments',
            'edit.shipments',
            'delete.shipments',
            'track.shipments',
            'view.warehouses',
            'manage.warehouses',
            'view.inventory',
            'update.inventory',
            'view.reports.sales',
            'view.reports.inventory',
            'view.reports.customers',
            'view.reports.financial',
            'export.reports.sales',
            'export.reports.inventory',
            'export.reports.customers',
            'export.reports.financial',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate([
                'name' => $permission,
                'guard_name' => 'web'
            ]);
        }
    }
}
